spring:
  cloud:
    gateway:
      metrics:
        enabled: true
      routes:
        - id: faculty-route
          uri: lb://faculty-service
          predicates:
            - Path=/api/faculties/**

        - id: subject-route
          uri: lb://subject-service
          predicates:
            - Path=/api/subjects/**

        - id: teacher-route
          uri: lb://teacher-service
          predicates:
            - Path=/api/teachers/**

        - id: classroom-route
          uri: lb://classroom-service
          predicates:
            - Path=/api/classrooms/**

        - id: specialty-route
          uri: lb://specialty-service
          predicates:
            - Path=/api/specialties/**

        - id: group-route
          uri: lb://group-service
          predicates:
            - Path=/api/groups/**

        - id: schedule-route
          uri: lb://schedule-service
          predicates:
            - Path=/api/schedule/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---
spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

