spring:
  datasource:
    url:      jdbc:postgresql://localhost:5432/subjects_db
    username: postgres
    password: root

  liquibase:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url:      jdbc:postgresql://postgres:5432/subjects_db
    password: ${POSTGRES_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
